name: crypto_tracker
description: Crypto Tracker - Team 22

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^7.0.0-nullsafety.0
  dio: 4.0.0
  intl: ^0.17.0
  equatable: ^2.0.2
  fl_chart: ^0.40.5
  flutter_bloc: ^7.0.1
  shared_preferences: ^2.0.5
  font_awesome_flutter: ^9.2.0
  syncfusion_flutter_datepicker: ^19.3.57
  url_launcher: ^6.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.0.4
  json_serializable: ^4.1.3
  test: ^1.3.0

flutter:
  uses-material-design: true
  fonts:
    - family: Oxygen
      fonts:
        - asset: fonts/Oxygen-Light.ttf
          weight: 400
        - asset: fonts/Oxygen-Regular.ttf
          weight: 600
        - asset: fonts/Oxygen-Bold.ttf
          weight: 800
  assets:
    - assets/images/
    - assets/images/card_dummy/
    - assets/images/contact_dummy/
